### ISSUE TITLE
case records - file upload in new case

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#103]
From tester feedback:
>On Create Case page, the file upload opens the file in the browser tab and you can’t use back button to go back to the case

**Comment by aaronstephenson** [comment]
This is purely a CSS thing... the drag-and-drop target area isn't very large, but it is there (essentially, directly around the text "or drop files here"). @mitch-wim could you make the drop target area co-extensive with the div around the drop text, or however you think is best?

**Comment by HansVraga** [comment]
@mitch-wim adjusted file upload to fill the entire screen for the upload target.
