### ISSUE TITLE
case records - error message troubles

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#104]
From user feedback
>When we tried to enter dates in incorrect chronology we got error messages, which made sense.  However, sometime we were unable to fix the error and close the message box.  To bypass that we has to suppress future error messages or close out of the browser.  Can we have these error messages just be warnings and that we can fully bypass by either leaving blank or entering a date with incorrect chronology?  We like the warnings but think we should keep it flexible.

**Comment by HansVraga** [comment]
We should consider moving error messages into toast notifications.

**Comment by aaronstephenson** [comment]
@mitch-wim are you currently working on this? Or is this what you mentioned in Slack about not being able to get all toasts to work? If the latter, I'll need to see your current work in your branch.

**Comment by aaronstephenson** [comment]
I changed the behavior of the date validation. Now it just gives a warning (with a toast once @mitch-wim merges his branch), and leaves the user-entered date, rather than clearing the date from the field.
