### ISSUE TITLE
dropdown lists - Staff dropdowns

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#107]
From tester feedback
>Analyst, Level 1 QC, and Level 2 QC dropdown lists should only have the current Fish and Wildlife staff members (in alphabetical order) with the ability to add or remove names as needed (or names drop off the list if not selected within an agreed upon time period).

**Comment by HansVraga** [comment]
Won't be surprised if there is more here than just some UI changes Mitch, but take a look to see if there is a field that indicates an active status for the employees available in that dropdown list.

**Comment by aaronstephenson** [comment]
I can limit the list to show only current staff, but the ability to add or remove names as needed is a new feature request, and out of scope.

**Comment by aaronstephenson** [comment]
I implemented the limited list (only current employees) on the case details page, but not the case list filter (since the users will likely want to be able to filter cases by former employees). I DID NOT implement the new feature request.

**Comment by aaronstephenson** [comment]
From tester feedback:
> PARTIALLY FIXED. The dropdown lists in the Case Record was fixed, but not the dropdown lists for Analyst and QC Reviewer in Filter Cases. Please update Filter Cases.

**Comment by aaronstephenson** [comment]
@HansVraga This was intentional on my part because there are the thousands of legacy cases with no-longer-active (-or-employed) users... do they not want to be able to search for cases by former users?

**Comment by HansVraga** [comment]
Closing - will create new issues for staff dropdown list fixes.
