### ISSUE TITLE
Legacy Data - additional cases needing import

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#108]
From tester feedback:
>There are about 50 new cases (some have a Final letter and some are currently in progress) that need to be entered into the database.  These are the cases that we have received and worked on while waiting for the finalization of the new database.  These cases have already been given a case number from our old system.  We can give you a list of old system case numbers for you to import as reference ids.

**Comment by HansVraga** [comment]
I intend to wait until they are using the new system before discussing the means to import their old data.

**Comment by aaronstephenson** [comment]
This will simply be handled by re-doing the data migration with their latest database.
