### ISSUE TITLE
final letter templates - creating a draft letter after one has been created

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#109]
From tester feedback:
>Seem to be having a problem creating a Draft Final Letter for Case ID 3400.  Created a draft letter at one point, made some changes to the database record to correct some data, and when we tried to create another draft, nothing happened after clicking on the Draft button

**Comment by aaronstephenson** [comment]
I'm not able to duplicate this problem locally. I'll try later in the QC environment.

**Comment by aaronstephenson** [comment]
This is a server side error, caused by bad string formatting of a date object. I have fixed it.
