### ISSUE TITLE
final letter templates - formatting changes

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#110]
From testing feedback:

- [x]  >Can the draft letter be changed to single space lines, instead of 1.15 spacing?
- [x]  >There should be comma after the salutation, not a colon.
- [x]  >Can the property address be on two lines, instead of one?
- [x]  >The date shouldn’t have a “0” in the number (e.g., it should be December 6, 2016, not December 06, 2016).
- [x]  >The prohibition date should be spelled out, like the map date (e.g., January 24, 2017, not 1983-10-01).
- [x]  >There is a missing space between "(CBRS)" and the sentence that is added when there is a flood insurance policy number ("The flood insurance policy number for the submitted request is 1151293722."

**Comment by aaronstephenson** [comment]
Done.
