### ISSUE TITLE
Change Alert Styling

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#122]
Two tasks:

- [ ] Change Warnings to sticky

- [ ] Change Style to be more apparant

Currently notifications/alerts informing the user of incorrect data entry appear at the bottom, and disappear (see screenshot). They should be more noticeable. Can we match our [banner,warning](http://wim.usgs.gov/styleguidebeta/#/ui#banners) color scheme from the styleguide? Can we either move the alert to the top, or switch back to the toast notification boxes of yore? (I prefer the box option)

![image](https://cloud.githubusercontent.com/assets/12058013/24251002/10c67408-0faf-11e7-8d96-dfaa038cca5f.png)

**Comment by HansVraga** [comment]
@aaronstephenson - I recall Mitch had a weird issue pushing his changes. Is this issue still addressed?

**Comment by aaronstephenson** [comment]
He mentioned that he was able to get the changes pushed and merged, but only after deleting his local repos and retrying. Or something to that effect.

**Comment by aaronstephenson** [comment]
@mitch-wim what's the status on this?
