### ISSUE TITLE
Case Details: Person selection in Case Assignment and Signoff section

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#129]
The Analyst, Level 1 QC, and Level 2 QC personnel should not be the same person. Adjust picklists to not show previously selected people for these fields (on a given case). 

Currently there is a bug that allows you to select the same person - you can recreate this by the following actions:

Set Paul Comlish as Analyst
Set Dana Write as L1QC
Paul Comlish is available as L2 QC.

**Comment by HansVraga** [comment]
Look to tackle this via throwing an alert if the user selects a person who has already been selected in one of the other roles. Essentially catching this issue at the data entry Validation instead of dynamic filtering of the selections.

**Comment by aaronstephenson** [comment]
With removal of the Level 2 QC (aka FWS Reviewer), this was an easy fix to allow dynamic filtering between just Analyst and QC.
