### ISSUE TITLE
Add Map Data Management page

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#132]
Initially we were looking at a widget to solve this, but the following chain revealed there is more needed for V1 here.

Aaron provided the following mock-up for the widget: [https://docs.google.com/a/usgs.gov/drawings/d/1tmSYLrEjO05W0ZoOf6sCCqSl2Kxo9krUNTFWxtVwvLs/edit?usp=sharing_eil&ts=58e68633](https://docs.google.com/a/usgs.gov/drawings/d/1tmSYLrEjO05W0ZoOf6sCCqSl2Kxo9krUNTFWxtVwvLs/edit?usp=sharing_eil&ts=58e68633)

Pauls responses, below, led to this conclusion from Aaron: 

**With these latest couple of suggestions, it sounds like what is needed is a separate, dedicated form (on its own page) for map data management. I will redo the widget mockup and turn it into a form.**

Paul's responses:
>This looks good.  Please use the term "superseded" rather than "deprecated".

>Also we would need to be able to add a new prohibition date.   Prohibition dates have their own relationship to Units, so maybe this needs to be a different widget? The business rule for this is if a new map adds an area to a CBRS unit then there will be exactly one new prohibition date associated with that unit.  Old prohibition dates don't become superseded or deprecated like maps do.   So we would just need to add new dates.

>Does this widget enable the user to flip a map number/date combo from effective to superseded?  Whenever we add a newly effective map number we will also need to retire the old one.  Something to consider.

**Comment by HansVraga** [comment]
(link to page if reference needed) https://docs.google.com/a/doi.gov/drawings/d/1tmSYLrEjO05W0ZoOf6sCCqSl2Kxo9krUNTFWxtVwvLs/edit?usp=sharing

**Comment by aaronstephenson** [comment]
I think this is now fully implemented, including the effective/superseded ("current") toggle.
