### ISSUE TITLE
Indicate superseded Map Unit/Number combinations in drop-down selections

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#133]
Upon completion of #132 - it will be possible for depreciated Unit/Number combinations to be drop-down menu selections in those fields. Add an indicator so the user can determine which selections are depreciated values.

![image](https://cloud.githubusercontent.com/assets/12058013/24781003/4c23ea60-1b0a-11e7-8c0a-de89d71c527e.png)

**Comment by HansVraga** [comment]
(title update to match their terminology)

**Comment by aaronstephenson** [comment]
Implemented
![superseded](https://user-images.githubusercontent.com/8713712/27924611-8506b108-6247-11e7-9846-7224982ccde4.PNG)
