### ISSUE TITLE
Workbench: Filtering by personnel

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#135]
Personnel fields in the filter show all users from the users table.
Limit the selections as follows:
First, show ALL active users in alphabetical order
Then, (in alphabetical order) show non-active users that have been identified as an Analyst or QC1 or QC2 in a previous case.
(the expectation is this will eliminate many in the current dropdown).

**Comment by aaronstephenson** [comment]
Implemented.
