### ISSUE TITLE
Add Report to Reporting module

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#138]
Request from cooperator
> For the report we want to be able to get the number of cases with a user supplied date status falling within a user supplied date range.  For example:
> 
> the number of cases with a received date falling in FY2016 (10/1/2015 - 9/30/2016)
> the number of cases with a close date falling between 1/1/2017 and 4/7/2017
> the number of cases that passed through a field office between x and y date. 
> 
> The report does not need to actually aggregate the data, just return the list of cases with the same exact columns that the "Days to each status complete" report has.  We would then export to csv for the aggregation and analysis.

**Comment by aaronstephenson** [comment]
So it sounds to me like they just want to be able to filter the "Days to each status complete" report.

**Comment by aaronstephenson** [comment]
Implemented.
