### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/CBRADMS#14]
- “Determinations by Unit” needed immediately

**Comment by HansVraga** [comment]
Once created, link to reports from the workbench.

**Comment by HansVraga** [comment]
Change "Time from request until assigned" to "Time from request to each status completion" (How long to initial review, QC, final, etc.)

**Comment by HansVraga** [comment]
Dividing into two Issues - Other reports can be post-release.

**Comment by aaronstephenson** [comment]
Added this report in PR #32
