### ISSUE TITLE
Implement better Date Selector

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/CBRADMS#18]
Default date input boxes are insufficient, maybe use a jQuery-like date picker.

**Comment by HansVraga** [comment]
(For consideration only) - the STNWeb date picker widget/interface:

<img width="229" alt="stndate-time" src="https://cloud.githubusercontent.com/assets/12058013/14858493/509cbdac-0c6e-11e6-9527-317f0e7595e3.PNG">

**Comment by HansVraga** [comment]
"Promoting" this issue to bug - we should address date pickers in a different way:
From user feedback:
>In date fields, the calendar dropdown does not appear for a Firefox user (Teresa Fish).

**Comment by aaronstephenson** [comment]
I have implemented the Angular2 "mydatepicker" module.
