### ISSUE TITLE
Add new case fields/tags?

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/CBRADMS#20]
- "On Hold" checkbox/tag?

- "Invalid" checkbox/tag?

**Comment by HansVraga** [comment]
"On Hold" and "Invalid" might be better to be values of the "status" as they describe case lifecycle states.

**Comment by aaronstephenson** [comment]
The trouble is that there is no "status" field. The "status" that shows up in the DMS UI is just a calculated field based on dates, the same as it was in Access.

**Comment by aaronstephenson** [comment]
I think the "status" idea doesn't quite fit, since these aren't normal states in the case lifecycle progression... they're extraordinary states. "Invalid" means this case shouldn't even be here, but we're holding on to it for recordkeeping, and "On Hold" means just that, and it could be indefinite. So the question goes back to what I originally asked... should these be just normal tags (like the "groups" CBRA currently uses), or permanent fields in the case table (like "Priority" already is). I'm leaning towards the latter, since they're similar to Priority. Or, maybe we convert Priority to a tag and treat them all as tags?

**Comment by aaronstephenson** [comment]
I decided to implement them as permanent fields on the Case model.
