### ISSUE TITLE
Need method for handling duplicates

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/CBRADMS#21]
ability to merge? or simple indicator?

**Comment by aaronstephenson** [comment]
They have a lot of legacy cases that are duplicates. I think the simplest solution is just an indicator. I implemented a Duplicate pick list (whose values are Case IDs) on the case detail page, so if there is a value there, it means it is a duplicate of the selected case. I'm not sure if anything more is necessary here (ability to search? ability to group?)

**Comment by HansVraga** [comment]
Closing - funcitonality relating to duplicates clarified from latest round of testing
