### ISSUE TITLE
Implement File Upload Constraints

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/CBRADMS#23]
- Limit file types
- Limit file sizes
- Display a warning message about it being a government system, etc
- Trigger for Signed Letter upload to auto-fill "Determination Date" field with current date (remains editable)

**Comment by aaronstephenson** [comment]
@HansVraga can you find the warning message text?

**Comment by aaronstephenson** [comment]
@HansVraga regarding the trigger, I'm not sure how to determine if a file is a "signed letter" unless the file always has a particular name (or regular expression), or if the user clicks a checkbox or something indicating that this file is a signed letter. What do you think?

**Comment by HansVraga** [comment]
I edited up a scary sounding blurb from the Dept. of Commerce - Throw a Fish and Wildlife logo in there and we're good?
-----

This is a United States Department of Fish and Wildlife system, which may be accessed and used only for official Government business. Inappropriate use of this system may subject violators to criminal and/or civil action.

All information on this system may be intercepted, recorded, read, copied, and disclosed by and to authorized personnel for official purposes, including criminal investigations. Access or use of this system by any person constitutes consent to these terms.

The seals, initials, and agency identification can not be used without the written permission of the agency.

------

**Comment by aaronstephenson** [comment]
Looks official to me, thanks. Any thoughts on the "signed letter" trigger?

**Comment by HansVraga** [comment]
I think the "signed letter" trigger may be in the wrong issue here - the determinations team will be the ones uploading a signed letter once it's available - from within their interface.

**Comment by HansVraga** [comment]
offline chat led to:
> a checkbox in the Case Files section, hidden until the status changes to "Awaiting Final Letter"

**Comment by aaronstephenson** [comment]
OK, I implemented everything except the warning message, which doesn't seem to belong here, so I moved that to the CBRARequests issues instead.
