### ISSUE TITLE
Add additional Reports / report Functionality

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#29]
- [x] Total Time to Resolution
- [x] Time from Request to each status complete
- [x] Total Number of Cases by Status
- [x] Enable export of reports into excel-friendly format (such as .csv)

**Comment by aaronstephenson** [comment]
All reports are working perfectly, but the CSV export is a little buggy (seems to be a disconnect between specified headers and actual listed data).

**Comment by aaronstephenson** [comment]
Fixed the CSV export bug.

**Comment by aaronstephenson** [comment]
>Reports generally work.  Export to csv works.  “Days to Resolution” and “Days to Each Status Complete” truncate results to 100 records, exported csv is also truncated.   
>>Yes, this 100 record limit is a leftover from my internal testing that I didn’t turn off. Part of the problem is that any more than 100 records on screen and the browser will slow down considerably. I could show all records if you insist, otherwise I could implement a clickable paging interface, with 100 records per “page” within the report. In any case, I will change the CSV exports to always include all records from the report, and not limit it to 100.
>>>100 records for browser, all records for csv

**Comment by HansVraga** [comment]
Closing - will create more specific reports issues.
