### ISSUE TITLE
Do not allow Deleting of active Tags

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#47]
If a tag is applied to any case ("Active Tag"), do not allow a user to delete it. Force them to remove it from every case it is attached to before allowing delete.

If a user tries to delete an Active Tag, give the following notification:

"This tag cannot be removed because it is assigned to one or more determination cases"

**Comment by aaronstephenson** [comment]
Implemented.

**Comment by aaronstephenson** [comment]
>Tags functionality works well except that we could not delete a tag (even after untagging the child cases)
>>What would be the preferred workflow: untag cases then delete tag, or delete tag and auto-untag cases?
>>>Delete and auto untag

**Comment by aaronstephenson** [comment]
Implemented.
