### ISSUE TITLE
Change "CBRA Determination Management" Heading to "CBRS Determinations Management" 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#48]
![image](https://cloud.githubusercontent.com/assets/12058013/18442237/000de398-78de-11e6-98a8-4308a9d02d6a.png)

Change the above to read "CBRS Determinations Management"

**Comment by aaronstephenson** [comment]
I changed this ages ago. Not sure why they would see the old name. Current live apps show the new name.
