### ISSUE TITLE
Change QC Reviewer label

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#55]
•	Change “QC Reviewer” label  to “Level 1 QC” and FWS Reviewer label to “Level 2 QC”

**Comment by aaronstephenson** [comment]
Done. I just changed the labels of those two fields on the Workbench Details form. The actual field names in the models and the DB remain unchanged. Eventually, I would like to eventually update the code with the new names, but it would require more-than-trivial refactoring.
