### ISSUE TITLE
Enable editing of date field after analyst is populated

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#57]
From cooperator:

> Once you enter analyst and date and hit save it’s impossible to edit the field.

_I assume the date field in question is obvious_ - @aaronstephenson - _but if not let me know_

**Comment by aaronstephenson** [comment]
I was not able to reproduce this behavior, so you'll need to ask them for clarification.

**Comment by HansVraga** [comment]
Paul has confirmed this is no longer an issue.
