### ISSUE TITLE
Remove auto-fill of Analyst date when Analyst is populated

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#59]
From Cooperator
>Remove auto-fill of analyst date under “case signoff”, because the workflow is to first assign a case to an analyst.  It will usually be several days until the analyst signs off on the case.   Therefore, the date will almost never be the current system date.

**Comment by HansVraga** [comment]
I will ask if once that field is populated if the assumption is the analyst is signing off.

**Comment by HansVraga** [comment]
So, the workflow (at this stage of the determination) has the assignment of an Analyst separate from sign-off of the Analyst.

**Comment by aaronstephenson** [comment]
Done.
