### ISSUE TITLE
Enforce "On Hold" checkbox on details updates

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#60]
From cooperator:
>Need a prompt when you enter a date in the analyst case sign-off field to uncheck On Hold box (if it is checked), because you can’t finish a case that is on hold.

**Comment by HansVraga** [comment]
I will ask if "On Hold" should do one of the following:

1. Lock all editing of the Case Details until unchecked
2. Prevent update of any case details that would change the case status
3. Prevent filling in "Analyst Sign-off date" until unchecked

**Comment by HansVraga** [comment]
On Hold should:

Prevent filling in "Analyst Sign-off date" until unchecked.

**Comment by aaronstephenson** [comment]
Implemented as a toggle that disables the analyst date field. Also disabled (on toggle) the other date fields that affect status (level 1 qc, level 2 qc, final letter, close) to prevent any possible status changes.
