### ISSUE TITLE
Enforce chronological Date values across life-cycle of determination

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#62]
From Cooperator:
>Create control (i.e., warning message) for dates when they don’t go in chronological order (request date<=field office<=hq<=analyst<=qc1<=qc2<=final letter<=close

**Comment by HansVraga** [comment]
Hard stop when population of a date breaks the rule - force a re-entry of the current date (or edit of a previous one).
_I wonder: if there is any date auto-populated if we could run into trouble here. For instance, (though we are to remove this function) the analyst date was auto-populated when analyst was populated, if this was in place, and someone had a future hq date, what sort of error would occur when someone populated the analyst field?_

**Comment by aaronstephenson** [comment]
Implemented, including strict chronological order enforcement. Also, the auto-populated date behavior has been removed.
