### ISSUE TITLE
Update output of final letter

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#63]
Update the text of the final letter to specifications of FWS CBRA team

**Comment by HansVraga** [comment]
Will ask for this text.

**Comment by aaronstephenson** [comment]
I still haven't received this. Could you request it?

**Comment by HansVraga** [comment]
Paul sent on the letter and instructions.
See the attached word document with comments.  

All dates should be in long date format e.g. November 1, 2016.

The logic for the "Determination statement" is based on the value of the "Determination field":

If determination is "In":

	This property is within [UNIT TYPE] Unit [UNIT].  The prohibition date on Federal flood insurance is [PROHIBITION DATE].

If determination is "Out":

	This property is not located within a System unit or an OPA of the CBRS.

If Determination is "Partially In/Structure Out:

	This property is partially located within [UNIT TYPE] Unit [UNIT]. The existing structure located on the property is not within Unit [UNIT].


If Determination is "Partially In/Structure In":

	This property is partially located within [UNIT TYPE] Unit [UNIT]. The existing structure located on the property is within Unit [UNIT]. The prohibition date on Federal flood insurance is [PROHIBITION DATE].

If Determination is Partially In/No Structure:

	This property is partially located within [UNIT TYPE] Unit [UNIT]. There is no existing structure located on the property. The prohibition date on Federal flood insurance is [PROHIBITION DATE].

**Comment by aaronstephenson** [comment]
Implemented.
