### ISSUE TITLE
Special Upload Button for Signed Determination

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#64]
From cooperator:

> Need a separate upload field to keep the final letter distinct and to allow system to automatically send that file to the requester.  This means we’ll need a separate upload button.

We'll need:
- [x] Said button "Signed Letter Upload"
- [x] The system to attach that letter to an email message and send it to the requestor
- [x] That file to also be attached to the case

**Comment by HansVraga** [comment]
- [ ] We should also remove the "signed letter" option in the current case details upload (IIRC that is in there)

**Comment by aaronstephenson** [comment]
Implemented
