### ISSUE TITLE
Enhancement Request: Email Integration

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#68]
From cooperator:

> New functionality: email from inside the system? Discuss level of effort.  We wouldn’t need this until we are ready to roll out to public.  
> We would like an auto-generated email confirmation with the same content as the case summary to be emailed to the requester.  
> Many times we need to email back and forth with requesters.  We believe that it would be appropriate to have this happen within the system.  Otherwise we will need to do the emailing outside the system then save as pdf and upload.  We would like to discuss the level of effort or other suggestions you may have.

**Comment by HansVraga** [comment]
Would need:
1. What emails they want auto-generated with Text, Subject

**Comment by HansVraga** [comment]
This enhancement can wait until after go-live.

**Comment by aaronstephenson** [comment]
Implemented.
