### ISSUE TITLE
Create new case using Case Details

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#69]
At initial Release, only authenticated users will create cases using the case ~~creation forms. We will need to require login to the CBRS system to access these forms.~~ details screen.

**Comment by aaronstephenson** [comment]
I'm strongly leaning towards leaving the CBRA Requests open (and unused for the time being), and using a blank Case Details form as the Create Case tool. The biggest reason is this avoids having to duplicate the authentication system from CBRA DMS onto CBRA Requests, and then trying to manage user state between the two apps.

**Comment by aaronstephenson** [comment]
I have the blank Case Details page working, but I still need to implement some validations. What are your thoughts here? @HansVraga

**Comment by HansVraga** [comment]
@aaronstephenson 
I'm on board. Changed the issue accordingly. We can probably get CBRS folks to test this (or I can test) to help refine validations as soon as you have your first pass in.

**Comment by aaronstephenson** [comment]
Implemented. I stripped out the tag, comment, and case object fields, leaving just the property, requester, and casefile object fields, which matches the public cbrarequests form's available fields.
