### ISSUE TITLE
Case received and final determination emails

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#70]
This issue describes the two automatic email notifications desired at release. Both are to have the reply-to address of "cbra@fws.gov"
- [x] Add an email from the system that is sent to the requester at case creation. 
- [x] Add an email from the system that is sent to the requester once the final letter is uploaded.

**Comment by HansVraga** [comment]
For Case Creation:
Subject: Coastal Barrier Resources Act Determination Request Received
Body: Reference Number: [Public Case ID]

**Comment by HansVraga** [comment]
For Final Letter:
Attach the Final Letter file.
Subject: Coastal Barrier Resources Act Determination Case # [Public Case ID]
Body: 

Dear Requester,

Attached is the Coastal Barrier Resources Act determination that you requested from the U.S. Fish and Wildlife Service.  If you have any questions about this determination, please contact Teresa Fish, Program Specialist, at (703) 258-2171 or e-mail us at cbra@fws.gov.

**Comment by aaronstephenson** [comment]
Implemented
