### ISSUE TITLE
Clear Null dates 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#81]
After data migration, some dates were set to 1/1/1970. These should all be cleared.

**Comment by aaronstephenson** [comment]
In the migration script, I was setting null request dates to UNIX Epoch zero because the request_date field is set to not allow nulls. Should we instead allow nulls?

**Comment by HansVraga** [comment]
Any way we could pull some trickery where if the date is UNIX epoch the field is displayed as "Not Set" in the client?

**Comment by aaronstephenson** [comment]
After some consideration, I'd rather not play around with the data display, and simply allow null request dates. It bothers my DBA sensibilities, but the data came to us dirty, and we can't clean all their messes for them.
