### ISSUE TITLE
Fix Improper tagging following Data import

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#82]
From CBRS folks:
>All cases appear to be tagged with "HH Hunt Homes - Island Cove", which is not correct.  In general we do not think that the conversion of groups to tags worked and that cases are not tagged with their old group.

Will need to address/remove/properly assign tags.

**Comment by aaronstephenson** [comment]
This is actually not true, all cases are NOT tagged with this. It's just that this value is the first item in the drop-down select list. But to make this more apparent, I went ahead and put an empty string as the first item in the drop-down select list, so nothing appears by default until you click the down arrow.
