### ISSUE TITLE
Users could not save data

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#83]
Need to troubleshoot and fix so they can test the whole workflow

**Comment by aaronstephenson** [comment]
There's a 500 error due to non-parsing JSON on the case post. I'll investigate tomorrow.

**Comment by aaronstephenson** [comment]
This works in my local dev environment when I disable the email module, but results in a 500 error when I enable it. My guess is that there is something misconfigured with email on the server. I will investigate more tomorrow.

**Comment by aaronstephenson** [comment]
This works fine in the ECOS QA server too, even with email enabled. I was able to edit and save an existing case, and create and save a new case. I don't see any issues here.
