### ISSUE TITLE
Unable to use File Drag and Drop

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#85]
Users reported to be unable to drag and drop files in any case.
Firefox was the browser being used.

**Comment by HansVraga** [comment]
I wonder if this is related to #83

**Comment by aaronstephenson** [comment]
Not relaced to #83. This is purely a Javascript/HTML5 problem. Need Mitch to weigh in here. Yo @mitchas !

**Comment by aaronstephenson** [comment]
I figured it out. It was just a misplaced div. I put it in the proper place and now drag-and-drop works.
