### ISSUE TITLE
File Select Speed and List Style

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/CBRADMS#89]
Both need to be improved (the file select in particular is slow and freezes the screen momentarily, and the file upload list gets ugly (and spills outside its div) when there is more than one listed), but I don't really have the time or talent for this particular task. @HansVraga could you find someone else to take this?

**Comment by HansVraga** [comment]
@mitchas between/after your SW trends work, can you take a look at this?

**Comment by aaronstephenson** [comment]
Also, regarding style, I made some inline style edits to some of the HTML pages (mostly the case details page)... could you take a look at those and change them to proper CSS using the style.css file and class references and such? Thanks.

**Comment by HansVraga** [comment]
@mitch-wim has made the appropriate updates.
