### ISSUE TITLE
Workbench - Status field

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#95]
From testing feedback:
>Filter case holds default status parameter (“in progress” cases) when a user makes a new filter.  For example, if you want to search for a “final” case by entering the case number and clicking search, the case will not be found because it is not in progress (received, awaiting final letter, etc).  We worked around this by manually selecting final or empty for the status parameter. The filter should be empty for status on a new search without having to manually clear it.  Also could “in progress” be a choice in the status menu?

**Comment by aaronstephenson** [comment]
I changed this behavior so that no selection in the Status field literally means no selection, and not Open. I also added the an 'Open' choice to the status list.
