### ISSUE TITLE
workbench - filter history

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#97]
From testing feedback:
>When navigating from the workbench to and from a case, the workbench does not hold the filter but reverts to the default workbench.  Hitting the back button and workbench button both clear the user defined filter and apply the default workbench filter.  The user should return to their workbench.  Can the case page come up in a separate tab?

**Comment by HansVraga** [comment]
Mitch - Don't have the page open up in a separate tab. But you should see if you can make use of local storage or some other means to save the last set of filter choices for a user.

**Comment by aaronstephenson** [comment]
I experimented with session storage, but I think an app service might be more appropriate. I'll think about it tonight and revisit tomorrow.

**Comment by aaronstephenson** [comment]
After far too many hours failing and trying to get Angular services to work with state variables the way they're documented, I went back to using session storage, and this works fine now. @HansVraga I would really appreciate some fresh eyes on this Angular snafu, maybe in a dev call.
