### ISSUE TITLE
workbench - Awaiting final letter / Close date filtering issues

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#98]
From Testing Feedback:
>A case that has all dates entered except “Close Date” indicates a status of “Awaiting Final Letter” but doesn’t show up on workbench when filtering on Awaiting Final Letter.   Answer: you can’t have a final letter date without closed date.  Close date is equal to final letter date except if final letter date is null.  We do this because there are times where we do not send an official final letter but the case is closed.  When user selects final letter date, close date should be set to final letter date.

**Comment by HansVraga** [comment]
Mitch when you have the application running ping me and we should take a look at this - this request is confusing but I think we can figure it out once we take a look at the system.

**Comment by aaronstephenson** [comment]
I'm really confused by what they're saying here. All I've done with the status calculations is duplicate the logic from their old system.

Here's the query from their Access DB:
```
SELECT 
IIf(Determinations.Close_Date Is Not Null And Determinations.Final_Letter_Date Is Null,"Closed with no Final Letter",
IIf(Determinations.Close_Date Is Not Null,"Final",
IIf(Determinations.FWS_Concurrence_Date Is Not Null,"Awaiting Final Letter",
IIf(Determinations.[D] Is Not Null,"Awaiting FWS Review",
IIf(Determinations.Recommendation_Date Is Not Null,"Awaiting QC","Received")))))
AS Date_Status
FROM Determinations;
```

Here's the query from Django:
```
if self.close_date and not self.final_letter_date:
	return 'Closed with no Final Letter'
elif self.close_date:
	return 'Final'
elif self.fws_reviewer_signoff_date:
	return 'Awaiting Final Letter'
elif self.qc_reviewer_signoff_date:
	return 'Awaiting Level 2 QC'
elif self.analyst_signoff_date:
	return 'Awaiting Level 1 QC'
else:
	return 'Received'
```

Field names are slightly different between the two systems, but what's the real difference here? What are they asking?

**Comment by HansVraga** [comment]
Asking the CBRS folks about this one.

**Comment by HansVraga** [comment]
Clarification from Paul:

> When a case is given a final letter date, it is by definition closed on that same date.  Currently if a user selects a final letter date but leaves close date null, the case goes into a sort of in-between status that does not meet our logical definition of "Awaiting final letter" or "Final".  So it doesn't come up when you try to filter by status, because it isn't an actual status.
> 
> To fix this:
> 
> When a user selects a final letter date, the close date should be automatically set to equal final letter date.  However, a user should be able to select a close date while leaving final letter date null (giving the case the status "closed with no final letter").  
> 
> So we would like the system to add the close date when the user enters the final letter date.

**Comment by aaronstephenson** [comment]
I have implemented the auto-close as Paul suggests, where setting an entry in the final letter date field will set the close date field to the same value.
